version: "3"
services:
  db:
    build: ./Db
    image: bookit_db:dev

  app:
    build: ./App
    image: bookit_app:dev
    links:
      - db
    ports:
      - "80:80"
  web:
    build: ./web
    image: bookit_web:dev
    links:
      - app
    ports:
      - "3000:80"
      - "443:443"
